steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - gcf_hello_world
  - --region=us-east-1
  - --source=.
  - --trigger-http
  - --runtime=nodejs8